import asyncio
import smtplib
import logging
from email.message import EmailMessage
from app.core.config import settings

logger = logging.getLogger(__name__)

def _get_base_template(title: str, content: str, color: str = "#0f172a") -> str:
    """Provides a highly formal, corporate HTML email shell."""
    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{ font-family: 'Inter', 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #f1f5f9; margin: 0; padding: 40px 0; }}
            .container {{ max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06); border: 1px solid #e2e8f0; }}
            .header {{ background-color: {color}; padding: 30px; text-align: center; border-bottom: 3px solid rgba(0,0,0,0.1); }}
            .header h1 {{ color: #ffffff; margin: 0; font-size: 22px; font-weight: 600; letter-spacing: 0.5px; text-transform: uppercase; }}
            .content {{ padding: 40px 35px; color: #334155; line-height: 1.6; font-size: 15px; }}
            .footer {{ background-color: #f8fafc; padding: 25px; text-align: center; color: #64748b; font-size: 12px; border-top: 1px solid #e2e8f0; }}
            .box {{ background: #f8fafc; border-left: 4px solid {color}; padding: 20px; margin: 25px 0; border-radius: 0 6px 6px 0; }}
            .label {{ font-weight: 600; color: #0f172a; width: 100px; display: inline-block; }}
            .signature {{ margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 20px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>{title}</h1>
            </div>
            <div class="content">
                {content}
                <div class="signature">
                    <p style="margin:0; font-weight: 600; color: #0f172a;">Sentinel Administration</p>
                    <p style="margin:0; font-size: 13px; color: #64748b;">Human Resources & Integrity Department</p>
                </div>
            </div>
            <div class="footer">
                <p style="margin: 0 0 10px 0;">This is an official automated communication generated by the Sentinel Work Integrity System.</p>
                <p style="margin: 0;"><strong>Do not reply directly to this email.</strong></p>
            </div>
        </div>
    </body>
    </html>
    """


def _send_email_sync(to_email: str, subject: str, html_body: str):
    """Synchronous core wrapped by asyncio.to_thread"""
    if not settings.SMTP_HOST or not settings.SMTP_USER:
        logger.warning(f"SMTP not configured — skipping email to {to_email}")
        return

    msg = EmailMessage()
    msg['Subject'] = subject
    msg['From'] = settings.SMTP_FROM_EMAIL or settings.SMTP_USER
    msg['To'] = to_email
    msg.add_alternative(html_body, subtype='html')

    try:
        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
            server.starttls()
            server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
            server.send_message(msg)
            logger.info(f"Email dispatched to {to_email} — subject: '{subject}'")
    except Exception as e:
        logger.error(f"Failed to send email to {to_email}: {e}")


async def send_task_assignment(employee_email: str, employee_name: str, task_title: str, priority: str):
    subject = f"Notice: Official Task Assignment - {task_title}"
    content = f"""
        <p>Dear {employee_name},</p>
        <p>This is to formally notify you that a new administrative task has been assigned to your queue via the Sentinel system.</p>
        <div class="box">
            <p style="margin:0 0 10px 0;"><span class="label">Task ID:</span> {task_title}</p>
            <p style="margin:0;"><span class="label">Priority:</span> <span style="text-transform: uppercase;">{priority}</span></p>
        </div>
        <p>Please launch your Sentinel Desktop Application at your earliest convenience to review the full details and specifications of this assignment.</p>
    """
    html = _get_base_template("Task Assignment Notice", content, color="#4f46e5")
    await asyncio.to_thread(_send_email_sync, employee_email, subject, html)


async def send_leave_decision(employee_email: str, employee_name: str, status: str, admin_response: str):
    subject = f"Notice: Leave Application Decision - {status.upper()}"
    color = "#059669" if status == "approved" else "#dc2626"
    content = f"""
        <p>Dear {employee_name},</p>
        <p>Your recent formal leave application has undergone administrative review. The final decision is detailed below.</p>
        <div class="box">
            <p style="margin:0 0 10px 0;"><span class="label">Status:</span> <strong style="color: {color}; text-transform: uppercase;">{status}</strong></p>
            <p style="margin:0;"><span class="label">Admin Note:</span> {admin_response or 'No additional administrative notes provided.'}</p>
        </div>
        <p>If you require further clarification regarding this decision, please contact your immediate supervisor or Human Resources.</p>
    """
    html = _get_base_template("Leave Application Decision", content, color=color)
    await asyncio.to_thread(_send_email_sync, employee_email, subject, html)


async def send_flag_warning(employee_email: str, employee_name: str, note: str):
    subject = "Notice: Sentinel System Warning"
    content = f"""
        <p>Dear {employee_name},</p>
        <p>The Sentinel Administration is issuing a formal notice regarding recent anomalous activity detected during your logged work sessions.</p>
        <div class="box">
            <p style="margin:0;"><span class="label" style="width:130px;">Admin Directive:</span> {note}</p>
        </div>
        <p>As per company policy, all personnel are required to maintain strict compliance with our work integrity and productivity guidelines.</p>
        <p>Further anomalous activity may result in an escalation of this matter to Human Resources.</p>
    """
    html = _get_base_template("Official Administrative Warning", content, color="#d97706")
    await asyncio.to_thread(_send_email_sync, employee_email, subject, html)


async def send_flag_escalation(employee_email: str, employee_name: str, note: str):
    hr_email = getattr(settings, "HR_ESCALATION_EMAIL", settings.SMTP_FROM_EMAIL)
    subject = f"URGENT Notice: Activity Escalation - {employee_name}"
    content = f"""
        <p>Dear {employee_name} and Human Resources,</p>
        <p>Continuous or severe anomalous patterns have been validated on the Sentinel network. This constitutes a direct breach of integrity guidelines.</p>
        <p><strong>This incident has been formally escalated for administrative review.</strong></p>
        <div class="box">
            <p style="margin:0;"><span class="label" style="width:130px;">Escalation Note:</span> {note}</p>
        </div>
        <p>A senior Human Resources representative will contact you shortly to schedule a formal review of this incident.</p>
    """
    html = _get_base_template("Formal Incident Escalation", content, color="#dc2626")

    await asyncio.to_thread(_send_email_sync, employee_email, subject, html)
    if hr_email and hr_email != employee_email:
        await asyncio.to_thread(_send_email_sync, hr_email, subject, html)